task:
  universal:
    - 'SHELL'
    - 'PYTHON'
    - 'PROCEDURE'
    - 'SQL'
    - 'SPARK'
    - 'FLINK'
    - 'HTTP'
    - 'MR'
  cloud:
    - 'EMR'
  logic:
    - 'SUB_PROCESS'
    - 'DEPENDENT'
    - 'CONDITIONS'
    - 'SWITCH'
    - 'NEXT_LOOP'
    - 'SURVEIL'
  dataIntegration:
    - 'SEATUNNEL'
    - 'DATAX'
    - 'SQOOP'
  dataQuality:
    - 'DATA_QUALITY'
  other: