task:
  universal:
    - 'SHELL'
    - 'PYTHON'
    - 'PROCEDURE'
    - 'SQL'
    - 'SPARK'
    - 'FLINK'
    - 'HTTP'
    - 'MR'
    - 'DINKY'
    - 'FLINK_STREAM'
    - 'HIVECLI'
  cloud:
    - 'EMR'
    - 'K8S'
  logic:
    - 'SUB_PROCESS'
    - 'DEPENDENT'
    - 'CONDITIONS'
    - 'SWITCH'
    - 'NEXT_LOOP'
    - 'SURVEIL'
  dataIntegration:
    - 'SEATUNNEL'
    - 'DATAX'
    - 'SQOOP'
  dataQuality:
    - 'DATA_QUALITY'
  machineLearning:
    - 'JUPYTER'
    - 'MLFLOW'
    - 'OPENMLDB'
    - 'DVC'
    - 'SAGEMAKER'
    - 'PYTORCH'
  other:
    - 'PIGEON'
    - 'ZEPPELIN'
    - 'CHUNJUN'